using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Parallax : MonoBehaviour
{
    private float length, startPos;
    public GameObject cam;
    public float parallaxEffect;

    private void Start()
    {
        startPos = transform.position.x;
        length = GetComponent<SpriteRenderer>().bounds.size.x;
    }

    private void Update()
    {
        float temp = (cam.transform.position.x * (1 - parallaxEffect));
        float distance = (cam.transform.position.x * parallaxEffect);

        transform.position = new Vector3(startPos + distance, transform.position.y, transform.position.z);

        if (temp > startPos + length)
            startPos += length;
        else if (temp < startPos - length)
            startPos -= length;
    }

    public void Up()
    {
        transform.position = new Vector3(transform.position.x, 5, transform.position.z);
        /*if (transform.position.y < 10f)
            transform.position = new Vector3(transform.position.x, transform.position.y + 1f, transform.position.z);*/
    }

    public void Down()
    {
        transform.position = new Vector3(transform.position.x, 3, transform.position.z);
    }
}
